export {default as About} from "./about/About"
export {default as Contact} from "./contact/Contact"
export {default as Home } from "./home/Home"
export {default as Knowledge } from "./knowledge/Knowledge"
export {default as Projects } from "./projects/Projects"
export {default as NotFound } from "./not_found/NotFound"